### ISSUE TITLE
请问这个插件还维护吗？

### ISSUE THREAD

**Issue by ModyQyW** [zxx960/vite-plugin-prettier#2]
你好，请问这个插件还维护吗？我有兴趣参与。:D

**Comment by zxx960** [comment]
目前功能比较简单，就是想简化prettier的配置，非常欢迎一起维护，让插件功能更强大。
。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zxx960/vite-plugin-prettier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月23日(星期三) 晚上8:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zxx960/vite-plugin-prettier] 请问这个插件还维护吗？ (Issue #2)





 
你好，请问这个插件还维护吗？我有兴趣参与。:D
